const data = {
  pizzas: [
    {
      _id: "1",
      name: "Pizza Margarita",
      size: "Familiar 35cm",
      price: 8500,
      ingredients: ["Masa Artesanal", "Salsa Pomodoro", "Queso Mozzarella"],
    },
    {
      _id: "2",
      name: "Pizza Pepperoni",
      size: "Familiar 35cm",
      price: 8500,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Pepperoni",
      ],
    },
    {
      _id: "3",
      name: "Pizza Napolitana",
      size: "Familiar 35cm",
      price: 11500,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Tomate",
        "Jamón",
      ],
    },
    {
      _id: "4",
      name: "Pizza Vegetariana",
      size: "Familiar 35cm",
      price: 12500,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Tómate",
        "Aceitunas",
        "Champiñones",
        "Cebolla",
        "Pimentón",
      ],
    },
    {
      _id: "5",
      name: "Pizza Todas las Carnes",
      size: "Familiar 35cm",
      price: 13000,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Pepperoni",
        "Jamón",
        "Chorizo",
        "Carne",
      ],
    },
    {
      _id: "6",
      name: "Pizza Mechada Luco",
      size: "Familiar 35cm",
      price: 12000,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Mechada",
      ],
    },
    {
      _id: "7",
      name: "Pizza Mechada",
      size: "Familiar 35cm",
      price: 11500,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Tomate",
        "Cebolla",
        "Carne Mechada",
      ],
    },
    {
      _id: "8",
      name: "Pizza Carne BBQ",
      size: "Familiar 35cm",
      price: 12500,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Carne",
        "Tocino",
        "Cebolla",
        "Salsa BBQ",
      ],
    },
    {
      _id: "9",
      name: "Pizza Pollo BBQ",
      size: "Familiar 35cm",
      price: 12500,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Pollo",
        "Tocino",
        "Cebolla",
        "Salsa BBQ",
      ],
    },
    {
      _id: "10",
      name: "Pizza Granjera",
      size: "Familiar 35cm",
      price: 13500,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Pollo",
        "Tocino",
        "Choricillo",
        "Cebolla",
        "Choclo",
      ],
    },
    {
      _id: "11",
      name: "Pizza Cuatro Estaciones",
      size: "Familiar 35cm",
      price: 9500,
      ingredients: [
        "2 Rebanadas de Pepperoni",
        "2 Rebanadas de Margarita",
        "2 Rebanadas de Primavera",
        "2 Rebabadas de Napolitana",
      ],
    },
    {
      _id: "12",
      name: "Pizza Super Española",
      size: "Familiar 35cm",
      price: 12000,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Pepperoni",
        "Chorizo",
        "Jamon",
        "Pimentón",
        "Choclo",
        "Aceitunas",
      ],
    },
    {
      _id: "13",
      name: "Pizza Mexicana",
      size: "Familiar 35cm",
      price: 12000,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Tomate",
        "Jalapeños",
        "Carne",
        "Pepperoni",
        "Merken",
      ],
    },
    {
      _id: "14",
      name: "Pizza Primavera",
      size: "Familiar 35cm",
      price: 11000,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Choclo",
        "Jamón",
      ],
    },
    {
      _id: "15",
      name: "Pizza Caprese",
      size: "Familiar 35cm",
      price: 10500,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Tomate",
        "Salsa Pesto",
      ],
    },
    {
      _id: "16",
      name: "Pizza Hawaiana",
      size: "Familiar 35cm",
      price: 11500,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Jamón",
        "Piña 🍍",
      ],
    },
    {
      _id: "17",
      name: "Pizza Margarita",
      size: "XL 40cm",
      price: 11000,
      ingredients: ["Masa Artesanal", "Salsa Pomodoro", "Queso Mozzarella"],
    },
    {
      _id: "21",
      name: "Pizza Pepperoni",
      size: "XL 40cm",
      price: 12000,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Pepperoni",
      ],
    },
    {
      _id: "32",
      name: "Pizza Napolitana",
      size: "XL 40cm",
      price: 14000,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Tomate",
        "Jamón",
      ],
    },
    {
      _id: "43",
      name: "Pizza Vegetariana",
      size: "XL 40cm",
      price: 15000,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Tómate",
        "Aceitunas",
        "Champiñones",
        "Cebolla",
        "Pimentón",
      ],
    },
    {
      _id: "54",
      name: "Pizza Todas las Carnes",
      size: "XL 40cm",
      price: 14500,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Pepperoni",
        "Jamón",
        "Chorizo",
        "Carne",
      ],
    },
    {
      _id: "6",
      name: "Pizza Mechada Luco",
      size: "XL 40cm",
      price: 14500,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Mechada",
      ],
    },
    {
      _id: "75",
      name: "Pizza Mechada",
      size: "XL 40cm",
      price: 14000,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Tomate",
        "Cebolla",
        "Carne Mechada",
      ],
    },
    {
      _id: "86",
      name: "Pizza Carne BBQ",
      size: "XL 40cm",
      price: 15000,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Carne",
        "Tocino",
        "Cebolla",
        "Salsa BBQ",
      ],
    },
    {
      _id: "97",
      name: "Pizza Pollo BBQ",
      size: "XL 40cm",
      price: 15000,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Pollo",
        "Tocino",
        "Cebolla",
        "Salsa BBQ",
      ],
    },
    {
      _id: "107",
      name: "Pizza Granjera",
      size: "XL 40cm",
      price: 16000,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Pollo",
        "Tocino",
        "Choricillo",
        "Cebolla",
        "Choclo",
      ],
    },
    {
      _id: "11",
      name: "Pizza Cuatro Estaciones",
      size: "XL 40cm",
      price: 12000,
      ingredients: [
        "2 Rebanadas de Pepperoni",
        "2 Rebanadas de Margarita",
        "2 Rebanadas de Primavera",
        "2 Rebabadas de Napolitana",
      ],
    },
    {
      _id: "128",
      name: "Pizza Super Española",
      size: "XL 40cm",
      price: 14500,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Pepperoni",
        "Chorizo",
        "Jamon",
        "Pimentón",
        "Choclo",
        "Aceitunas",
      ],
    },
    {
      _id: "139",
      name: "Pizza Mexicana",
      size: "XL 40cm",
      price: 14500,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Tomate",
        "Jalapeños",
        "Carne",
        "Pepperoni",
        "Merken",
      ],
    },
    {
      _id: "140",
      name: "Pizza Primavera",
      size: "XL 40cm",
      price: 13500,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Choclo",
        "Jamón",
      ],
    },
    {
      _id: "158",
      name: "Pizza Caprese",
      size: "XL 40cm",
      price: 13000,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Tomate",
        "Salsa Pesto",
      ],
    },
    {
      _id: "167",
      name: "Pizza Hawaiana",
      size: "XL 40cm",
      price: 14000,
      ingredients: [
        "Masa Artesanal",
        "Salsa Pomodoro",
        "Queso Mozzarella",
        "Jamón",
        "Piña 🍍",
      ],
    },
    {
      _id: "178",
      name: "Arma tu pizza",
      size: "Familiar 35cm",
      price: 8500,
    },
    {
      _id: "178",
      name: "Arma tu pizza",
      size: "XL 40cm",
      price: 11000,
    },
  ],
  options: {
    extras: [
      {
        name: "Adicional Tomate",
        size: "N/A",
        price: 1000,
      },
      {
        name: "Adicional Cebolla",
        size: "N/A",
        price: 1000,
      },
      {
        name: "Adicional Pimiento",
        size: "N/A",
        price: 1000,
      },
      {
        name: "Champiñones Laminados",
        size: "N/A",
        price: 1000,
      },
      {
        name: "Adicional Aceitunas",
        size: "N/A",
        price: 1000,
      },
      {
        name: "Adicional Choclo",
        price: 1000,
      },
      {
        name: "Adicional Piña",
        size: "N/A",
        price: 1000,
      },
      {
        name: "Adicional Jalapeño",
        size: "N/A",
        price: 1000,
      },
      {
        name: "Adicional Pepperoni",
        size: "N/A",
        price: 1500,
      },
      {
        name: "Adicional Jamón",
        size: "N/A",
        price: 1500,
      },
      {
        name: "Adicional Tocino",
        size: "N/A",
        price: 1500,
      },
      {
        name: "Adicional Chorizo",
        size: "N/A",
        price: 1500,
      },
      {
        name: "Adicional Choricillo",
        size: "N/A",
        price: 1500,
      },
      {
        name: "Adicional Carne",
        size: "N/A",
        price: 1500,
      },
      {
        name: "Adicional Pollo",
        size: "N/A",
        price: 1500,
      },
      {
        name: "Adicional Anchoas",
        size: "N/A",
        price: 1500,
      },
      {
        name: "Bebida 2L",
        size: "N/A",
        price: 2000,
      },
    ],
  },
};

export default data;
